export const detailsFields = [
  "t.ticket_id",
  "t.email",
  "t.name",
  "t.phone",
  "t.device_sn",
  "t.device_name",
  "t.device_producer",
  "t.type",
  "t.issue",
  "t.status",
  "t.created",
  "t.lines",
  "t.postCode",
  "t.city",
  "t.device_cat",
  "t.lastStatusUpdate",
  "t.inWarehouse",
  "i.item_id",
  "s.shelve_id",
  "s.code",
  "t.damage_description",
  "t.damage_type",
  "t.result_type",
  "t.result_description",
]

export const listFields = [
  "t.ticket_id",
  "t.device_cat",
  "t.device_name",
  "t.device_producer",
  "t.status",
  "t.type",
  "t.created",
  "t.lastStatusUpdate",
]
